name: Update JSON from website

on:
  schedule:
    - cron: '*/1 * * * *' # Pokreće se svakih minut

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create sample JSON data
        run: |
          echo '{"success": true, "message": "Sample data"}' > data.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update JSON data"
          git push
